### ISSUE TITLE
ovf deploy crashes on apply after passing plan without issues

### ISSUE THREAD

**Issue by glipets** [hashicorp/terraform-provider-vsphere#1396]
### Terraform Version
Terraform v0.15.0 (similar issues on 14.4

### vSphere Provider Version
v1.26.0 and v1.25.0 
connecting to vshere vSphere version 6.7.0.44000

### Affected Resource(s)
ovf_deploy

```
### Terraform Configuration Files
terraform {
  required_providers {
    vsphere = {
      source = "hashicorp/vsphere"
      version = "1.26.0"
    }
  }
}

provider "vsphere" {
  user           = var.vsphere_user
  password       = var.vsphere_password
  vsphere_server = var.vsphere_server

  
  allow_unverified_ssl = true
}
#### RETRIEVE DATA INFORMATION ON VCENTER ####

data "vsphere_datacenter" "dc" {
  name =  var.datacenter
}
# Retrieve datastore information on vsphere (numbers start with 0)
data "vsphere_datastore" "datastore0" {
  name          = var.datastore.0
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_datastore" "datastore1" {
  name          = var.datastore.1
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_datastore" "datastore2" {
  name          = var.datastore.2
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_datastore" "datastore3" {
  name          = var.datastore.3
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_datastore" "datastore4" {
  name          = var.datastore.4
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_datastore" "datastore5" {
  name          = var.datastore.5
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_datastore" "datastore6" {
  name          = var.datastore.6
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_datastore" "datastore7" {
  name          = var.datastore.7
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_compute_cluster" "cluster" {
  name          = var.cluster
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name = var.network1
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_host" "host" {
  name = "172.26.239.232"
  datacenter_id = data.vsphere_datacenter.dc.id
  }

resource "vsphere_virtual_machine" "gw1" {
  name             = var.names[0]
  folder         = var.folder
  resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_id = data.vsphere_datastore.datastore6.id
  host_system_id = data.vsphere_host.host.id
  datacenter_id = data.vsphere_datacenter.dc.id
  #Below to make sure it will not wait for IP address to get assigned
  wait_for_guest_net_timeout = 0
  wait_for_guest_ip_timeout  = 0
  num_cpus = 4
  memory = 4096
  
  ovf_deploy {
    allow_unverified_ssl_cert = true

    local_ovf_path = "/home/ps/tf/ovf/Check_Point_SG_R80.40.ovf"
    disk_provisioning = "thin"
    ovf_network_map = {
      "VM Network" = data.vsphere_network.network.id
    }
  }
  vapp {
    properties = {
    "guestinfo.hostname" = "bob_server",
    "guestinfo.ipaddr_v4" = "10.2.1.50",
    "guestinfo.masklen_v4" = "24",
    "guestinfo.default_gw_v4" = "10.2.1.2",
    "guestinfo.eth1_ipaddr_v4" = "10.2.2.51",
    "guestinfo.eth1_masklen_v4" = "24",
    "guestinfo.primary" = "8.8.8.8",
    "guestinfo.secondary" = "8.8.4.4",
    "guestinfo.ftw_sic_key" = "vpn123",
    "guestinfo.download_info" = "true",
    "guestinfo.upload_info" = "true",
    "guestinfo.gateway_cluster_member" = "false",
    "guestinfo.configure" = "true",
  }
}
}
```

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Panic Output

root@ubuntu:/home/ps/tf/ottawa/garytest# terraform apply --auto-approve
vsphere_virtual_machine.gw1: Creating...

Stack trace from the terraform-provider-vsphere_v1.26.0_x4 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x101db80]

goroutine 42 [running]:
github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/ovfdeploy.(*OvfHelper).GetImportSpec(0xc00013ea50, 0xc000676790, 0xc00013ea50, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/ovfdeploy/ovf_helper.go:541 +0x480
github.com/hashicorp/terraform-provider-vsphere/vsphere.resourceVsphereMachineDeployOvfAndOva(0xc0006509a0, 0x130bc20, 0xc00061f6a0, 0x12a9640, 0xc0003bc660, 0x1)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vsphere/resource_vsphere_virtual_machine.go:1328 +0x14a
github.com/hashicorp/terraform-provider-vsphere/vsphere.resourceVSphereVirtualMachineCreate(0xc0006509a0, 0x130bc20, 0xc00061f6a0, 0x2, 0x216efe0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vsphere/resource_vsphere_virtual_machine.go:324 +0xa2a
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000596300, 0xc000444af0, 0xc00061e680, 0x130bc20, 0xc00061f6a0, 0x133c001, 0xc0003ba438, 0xc000253b90)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:305 +0x375
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000597780, 0xc0003a38e8, 0xc000444af0, 0xc00061e680, 0xc0003ba090, 0xc0005d2e38, 0x133de20)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000ebf0, 0x184ef70, 0xc00012efc0, 0xc000233500, 0xc00000ebf0, 0xc00012efc0, 0xc00014ca50)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:885 +0x8a5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1586f00, 0xc00000ebf0, 0x184ef70, 0xc00012efc0, 0xc0002334a0, 0x0, 0x184ef70, 0xc00012efc0, 0xc000179900, 0x1114)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3189 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000b2000, 0x1857a98, 0xc000956a80, 0xc0000fc100, 0xc0005d49c0, 0x21300a0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/google.golang.org/grpc/server.go:995 +0x482
google.golang.org/grpc.(*Server).handleStream(0xc0000b2000, 0x1857a98, 0xc000956a80, 0xc0000fc100, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/google.golang.org/grpc/server.go:1275 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00034c1d0, 0xc0000b2000, 0x1857a98, 0xc000956a80, 0xc0000fc100)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/google.golang.org/grpc/server.go:710 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/google.golang.org/grpc/server.go:708 +0xa5

Error: The terraform-provider-vsphere_v1.26.0_x4 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.

### Expected Behavior

I have a new vm machine built on vsphere server

### Steps to Reproduce
terraform apply results in the message above

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by koikonom** [comment]
Hi @glipets,

Thanks for reporting this issue. I will fix this in the next release.

**Comment by glipets** [comment]
so i discovered this occurred because the user didn't have permissions to create ovf. Once permissions were updated, the crash  no longer occurred. I this this is an issue with really bad/non-existent error message

**Comment by koikonom** [comment]
You are correct, when creating the import spec it can either return an error when submitting the request, or it can return an error as part of the response. I missed the first one.

**Comment by glipets** [comment]
Can you explain why my vapp is not working

  vapp {
    properties = {
     "iface" = "eth0",
     "hostname" = "GW1",
     "ipaddr_v4" = "10.2.2.10",
     "masklen_v4" = "24",
     "default_gw_v4" = "10.2.2.1",
     "eth1_ipaddr_v4": "172.25.62.240",
     "eth1_ipaddr_v4": "24",
     "primary": "8.8.8.8",
     "ftw_sic_key" = "vpn123",
     "download_info"  = "true",
     "upload_info" = "true",
     "gateway_cluster_member" = "false",
     "configure": "true",
  }
After apply

vsphere_virtual_machine.gw1: Still creating... [1m30s elapsed]

Error: error while creating vapp properties config unsupported vApp properties in vapp.properties: [upload_info configure iface download_info gateway_cluster_member]

  on test.tf line 70, in resource "vsphere_virtual_machine" "gw1":
  70: resource "vsphere_virtual_machine" "gw1" {



same config is working with ansible

     validate_certs: false
      inject_ovf_env: true
      properties:
        iface: "eth0"
#        ipstat_v4: "manually"
        hostname: "gary_gw"
        ipaddr_v4: "172.25.62.15"
        masklen_v4: "24"
        default_gw_v4: "172.25.62.240"
        eth1_ipaddr_v4: "10.2.2.51"
        eth1_masklen_v4: "24"
        primary: "8.8.8.8"
        ftw_sic_key: "vpn123"
        download_info: "true"
        upload_info: "true"
        gateway_cluster_member: "false"
        configure: "true"

**Comment by koikonom** [comment]
@glipets can you please check that all the properties defined in your config are also defined in the OVF template ?

**Comment by glipets** [comment]
terraform {
  required_providers {
    vsphere = {
      source = "hashicorp/vsphere"
      version = "1.26.0"
    }
  }
}

provider "vsphere" {
  user           = var.vsphere_user
  password       = var.vsphere_password
  vsphere_server = var.vsphere_server

  # If you have a self-signed cert
  allow_unverified_ssl = true
}
#### RETRIEVE DATA INFORMATION ON VCENTER ####

data "vsphere_datacenter" "dc" {
  name =  var.datacenter
}
# Retrieve datastore information on vsphere (numbers start with 0)
data "vsphere_datastore" "datastore0" {
  name          = var.datastore.0
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_datastore" "datastore1" {
  name          = var.datastore.1
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_datastore" "datastore2" {
  name          = var.datastore.2
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_datastore" "datastore3" {
  name          = var.datastore.3
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_datastore" "datastore4" {
  name          = var.datastore.4
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_datastore" "datastore5" {
  name          = var.datastore.5
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_datastore" "datastore6" {
  name          = var.datastore.6
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_datastore" "datastore7" {
  name          = var.datastore.7
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_compute_cluster" "cluster" {
  name          = var.cluster
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name = var.network1
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_host" "host" {
  name = "172.25.29.6"
  datacenter_id = data.vsphere_datacenter.dc.id
  }

resource "vsphere_virtual_machine" "gw1" {
  name             = var.names[0]
  folder         = var.folder
  resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_id = data.vsphere_datastore.datastore6.id
  host_system_id = data.vsphere_host.host.id
  datacenter_id = data.vsphere_datacenter.dc.id
  #Below to make sure it will not wait for IP address to get assigned
  wait_for_guest_net_timeout = 0
  wait_for_guest_ip_timeout  = 0
  num_cpus = 4
  memory = 4096

  disk {
    label = "disk0"
    size  = "100"
  }

  ovf_deploy {
    allow_unverified_ssl_cert = true

    #local_ovf_path = "/home/ps/tf/ovf/Check_Point_SG_R80.40.ovf"
    local_ovf_path = "C:\\Users\\admin\\Downloads\\ovf\\Check_Point_SG_R80.40.ovf"

    disk_provisioning = "thin"
    ovf_network_map = {
      "VM Network" = data.vsphere_network.network.id
    }
  }
  vapp {
    properties = {
     "iface" = "eth0",
     "hostname" = "GW1",
     "ipaddr_v4" = "10.2.2.10",
     "masklen_v4" = "24",
     "default_gw_v4" = "10.2.2.1",
     "eth1_ipaddr_v4": "172.25.62.240",
     "eth1_ipaddr_v4": "24",
     "primary": "8.8.8.8",
     "ftw_sic_key" = "vpn123",
     "download_info"  = "true",
     "upload_info" = "true",
     "gateway_cluster_member" = "false",
     "configure": "true",
  }
}
}

my whole config is above. Are you saying i should have all the variable i have in vapp also in ovf_deploy section somehow ? Can you give me an example what it would look like on my config ?

**Comment by koikonom** [comment]
The vApp properties that you can set are defined in the `Check_Point_SG_R80.40.ovf`. 

What the error message actually says is that upload_info, configure, iface, download_info, and gateway_cluster_member are unsupported because they do not exist in the VM we built based on the OVF template. 

This means two things, either the properties have different names in the OVF template, or the resulting VM doesn't have these properties defined for some reason.

If you build a new VM from that OVF manually (through the vSphere UI) can you see all these vApp properties?

**Comment by glipets** [comment]
I see the following ovf:keys in the file (so the ones that are not working are on the top line
`grep ovf:key /home/ps/tf/ovf/Check_Point_SG_R80.40.ovf
      <Property ovf:key="default_values" ovf:type="string" ovf:value="admin_mgmt_name=&quot;admin&quot;&amp;download_info=&quot;true&quot;&amp;upload_info=&quot;true&quot;&amp;iface=&quot;eth0&quot;&amp;ipstat_v4=&quot;manually&quot;&amp;ipstat_v6=&quot;false&quot;">
      <Property ovf:key="solution_type" ovf:qualifiers="ValueMap{&quot;Standalone&quot;, &quot;Security Gateway&quot;, &quot;Security Management&quot;}" ovf:type="string" ovf:userConfigurable="false" ovf:value="Security Gateway">
      <Property ovf:key="hostname" ovf:type="string" ovf:userConfigurable="true">
      <Property ovf:key="eth2_ipaddr_v4" ovf:qualifiers="MaxLen(15)" ovf:type="string">
      <Property ovf:key="password_type" ovf:qualifiers="ValueMap{&quot;Hashed&quot;, &quot;Plain&quot;}" ovf:type="string" ovf:userConfigurable="true" ovf:value="Plain">
      <Property ovf:key="default_gw_v4" ovf:qualifiers="MaxLen(15)" ovf:type="string" ovf:userConfigurable="true">
      <Property ovf:key="admin_hash" ovf:password="true" ovf:type="string" ovf:userConfigurable="true">
      <Property ovf:key="ipaddr_v4" ovf:qualifiers="MaxLen(15)" ovf:type="string" ovf:userConfigurable="true">
      <Property ovf:key="masklen_v4" ovf:qualifiers="ValueMap{&quot;1&quot;, &quot;2&quot;, &quot;3&quot;, &quot;4&quot;, &quot;5&quot;, &quot;6&quot;, &quot;7&quot;, &quot;8&quot;, &quot;9&quot;, &quot;10&quot;, &quot;11&quot;, &quot;12&quot;, &quot;13&quot;, &quot;14&quot;, &quot;15&quot;, &quot;16&quot;, &quot;17&quot;, &quot;18&quot;, &quot;19&quot;, &quot;20&quot;, &quot;21&quot;, &quot;22&quot;, &quot;23&quot;, &quot;24&quot;, &quot;25&quot;, &quot;26&quot;, &quot;27&quot;, &quot;28&quot;, &quot;29&quot;, &quot;30&quot;, &quot;31&quot;, &quot;32&quot;}" ovf:type="string" ovf:userConfigurable="true" ovf:value="24">
      <Property ovf:key="eth1_ipaddr_v4" ovf:qualifiers="MaxLen(15)" ovf:type="string" ovf:userConfigurable="true">
      <Property ovf:key="eth1_masklen_v4" ovf:qualifiers="ValueMap{&quot;1&quot;, &quot;2&quot;, &quot;3&quot;, &quot;4&quot;, &quot;5&quot;, &quot;6&quot;, &quot;7&quot;, &quot;8&quot;, &quot;9&quot;, &quot;10&quot;, &quot;11&quot;, &quot;12&quot;, &quot;13&quot;, &quot;14&quot;, &quot;15&quot;, &quot;16&quot;, &quot;17&quot;, &quot;18&quot;, &quot;19&quot;, &quot;20&quot;, &quot;21&quot;, &quot;22&quot;, &quot;23&quot;, &quot;24&quot;, &quot;25&quot;, &quot;26&quot;, &quot;27&quot;, &quot;28&quot;, &quot;29&quot;, &quot;30&quot;, &quot;31&quot;, &quot;32&quot;}" ovf:type="string" ovf:userConfigurable="true" ovf:value="24">
      <Property ovf:key="ftw_sic_key" ovf:password="true" ovf:type="string" ovf:userConfigurable="true">
      <Property ovf:key="is_gateway_cluster_member" ovf:qualifiers="ValueMap{&quot;Yes&quot;, &quot;No&quot;}" ovf:type="string" ovf:userConfigurable="true" ovf:value="No">
      <Property ovf:key="tretiatry" ovf:qualifiers="MaxLen(15)" ovf:type="string">
      <Property ovf:key="primary" ovf:qualifiers="MaxLen(15)" ovf:type="string" ovf:userConfigurable="true">
      <Property ovf:key="secondary" ovf:qualifiers="MaxLen(15)" ovf:type="string">
      <Property ovf:key="proxy_port" ovf:type="string" ovf:userConfigurable="true">
      <Property ovf:key="proxy_address" ovf:type="string" ovf:userConfigurable="true">
      <Property ovf:key="ntp_primary" ovf:type="string" ovf:userConfigurable="true">
      <Property ovf:key="ntp_primary_version" ovf:qualifiers="ValueMap{&quot;1&quot;, &quot;2&quot;, &quot;3&quot;, &quot;4&quot;}" ovf:type="string" ovf:userConfigurable="true" ovf:value="4">
      <Property ovf:key="clish_commands" ovf:type="string" ovf:userConfigurable="true">
      <Property ovf:key="timezone" ovf:type="string">
      <Property ovf:key="additional_configuration" ovf:type="str`

**Comment by koikonom** [comment]
In the OVF I see there is a `default_values` key with a value of `"admin_mgmt_name=&quot;admin&quot;&amp;download_info=&quot;true&quot;&amp;upload_info=&quot;true&quot;&amp;iface=&quot;eth0&quot;&amp;ipstat_v4=&quot;manually&quot;&amp;ipstat_v6=&quot;false&quot;"`

If you wanted to override one of these values, for example set `admin_mgmt_name` to `administrator`, then I'd try something like this:
```
vapp {
  properties = {
     [... more properties ...]
     "default_values" = "admin_mgmt_name=&quot;administrator&quot;&amp;download_info=&quot;true&quot;&amp;
     upload_info=&quot;true&quot;&amp;iface=&quot;eth0&quot;&amp;ipstat_v4=&quot;manually&quot;&amp;ipstat_v6=&
     quot;false&quot;"
     [... more properties ...]
   }
}
```

That said, from the keys you got in the error message (`upload_info, configure, iface, download_info, and gateway_cluster_member`) two of them are still undefined. One `gateway_cluster_member`, which I think should be replaced with `is_gateway_cluster_member` and the other is `configure`, which I am not sure what it should be.

**Comment by glipets** [comment]
``  vapp {
    properties = {
     "default_values" = "admin_mgmt_name=&quot;administrator&quot;&amp;download_info=&quot;true&quot;&amp;upload_info=&quot;true&quot;&amp;iface=&quot;eth0&quot;&amp;ipstat_v4=&quot;manually&quot;&amp;ipstat_v6=&quot;false&quot;"
     #"default_values" = "iface=eth0; hostname"="GW2","hostname"="GW2","ipaddr_v4"="10.2.2.10", "
     #"iface" = "eth0",
     "hostname" = "GW-TF",
     "ipaddr_v4" = "172.25.62.16",
     "masklen_v4" = "24",
     "default_gw_v4" = "172.25.62.16",
  }

Trying to simplify it
So the above config doesn't work
Error: error while creating vapp properties config vApp property with userConfigurable=false specified in vapp.properties: [hostname default_values ipaddr_v4 masklen_v4 default_gw_v4]

If i remove default values, this will apply, but my machine will just be crashing all the time, after booting.
I believe because it doesn't know about eth0 variable even though i am trying to keep it as default at eth0

**Comment by koikonom** [comment]
I downloaded the OVF myself, imported it to the lab, and tried to start a new VM from it via the UI. I don't see any place where you have to set the interface name: 

<img width="778" alt="image" src="https://user-images.githubusercontent.com/158027/116455850-71d0d800-a859-11eb-97fc-e110fd481900.png">

**Comment by glipets** [comment]
![image](https://user-images.githubusercontent.com/5975392/116474805-3244c480-a836-11eb-9a41-33964932721c.png)
![image](https://user-images.githubusercontent.com/5975392/116474828-3b359600-a836-11eb-97e9-59d69c77fc7e.png)
![image](https://user-images.githubusercontent.com/5975392/116474838-3ffa4a00-a836-11eb-97ce-4f138ab59bb4.png)
![image](https://user-images.githubusercontent.com/5975392/116474926-5b655500-a836-11eb-88f4-68be8b44a329.png)
So i can do OVF manually and then repeat everything in terraform with the same configuration. It works as far as terraform apply is concerned, but the VM i get via manual method works fine; the vm which is done via vm just goes up and down in perpetuity.  Is there  a chance we can get a zoom meeting going ?
