### ISSUE TITLE
Provider panic when `resource_pool_id` not returned

### ISSUE THREAD

**Issue by tejavar** [hashicorp/terraform-provider-vsphere#1582]
### Terraform Version
terraform 1.1.4

### vSphere Provider Version
Product Version: vsphere v2.0.2

### Affected Resource(s)
Issue occurred here: https://github.com/hashicorp/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_virtual_machine.go#L447

Segmentation violation is attempting to access something that has not been allocated yet and it seems to be the resource pool. 

### Terraform Configuration Files

```hcl

provider "vsphere" {
  user           = var.vsphere_user
  password       = var.vsphere_password
  vsphere_server = var.vsphere_server

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

variable "vsphere_user" {
  description = "VSphere Username"
  type        = string
  default     = "administrator@vsphere.local"
}

variable "vsphere_password" {
  description = "VSphere Password"
  type        = string
  default     = ""
}

variable "vsphere_server" {
  description = "VSphere server"
  type        = string
  default     = "vcenter.mgmt.dovetail-lab.ca"
}


resource "vsphere_resource_pool" "resource_pool" {
  name                    = "SANDBOX"
  parent_resource_pool_id = "${data.vsphere_compute_cluster.compute_cluster.resource_pool_id}"
}

```

### Debug Output

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x126455c]

goroutine 357 [running]:
github.com/hashicorp/terraform-provider-vsphere/vsphere.resourceVSphereVirtualMachineRead(0xc000295a00, 0x14351a0, 0xc0008e3e60, 0x237d940, 0xc000600000)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vsphere/resource_vsphere_virtual_machine.go:447 +0x17dc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0002575e0, 0x19e30a8, 0xc0006dba80, 0xc000295a00, 0x14351a0, 0xc0008e3e60, 0x0, 0x0, 0x0)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0002575e0, 0x19e30a8, 0xc0006dba80, 0xc000aa4d90, 0x14351a0, 0xc0008e3e60, 0xc00028f958, 0x0, 0x0, 0x0)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c228, 0x19e30a8, 0xc0006dba80, 0xc0006dbac0, 0xc0006dba80, 0x40b965, 0x16537a0)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0006b6000, 0x19e3150, 0xc0006dba80, 0xc0006ee720, 0xc0006b6000, 0xc0005da150, 0xc000b56ba0)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x16b5a40, 0xc0006b6000, 0x19e3150, 0xc0005da150, 0xc0006ee6c0, 0x0, 0x19e3150, 0xc0005da150, 0xc000874000, 0xbd6)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002bd500, 0x19ed138, 0xc000299380, 0xc000c30300, 0xc0005da060, 0x233e270, 0x0, 0x0, 0x0)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/google.golang.org/grpc/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0002bd500, 0x19ed138, 0xc000299380, 0xc000c30300, 0x0)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/google.golang.org/grpc/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000c03d0, 0xc0002bd500, 0x19ed138, 0xc000299380, 0xc000c30300)
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/google.golang.org/grpc/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/google.golang.org/grpc/server.go:857 +0x1fd

Error: The terraform-provider-vsphere_v2.0.2_x5 plugin crashed!
```

### Expected Behavior
A clear and concise description of what you expected to happen if this bug did not exist.

### Steps to Reproduce
Unable to reproduce with the customers code but he was able to reproduce reliably. I believe this had to do with the fact that the virtual machine was already created in the state but missing the resource id. 

### References

Workaround - Code was refactored to remove the resource pool data source and then create a dependency on the resource pool being created prior to the virtual machine being created. The virtual machine was removed and recreated and this resolved the issue.

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by tenthirtyam** [comment]
@tejavar - was the following provided in the original configuration:

```hcl
data "vsphere_datacenter" "datacenter" {
  name = var.vsphere_datacenter
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.vsphere_cluster
  datacenter_id = data.vsphere_datacenter.datacenter.id
}
```

This would be required to support the following:

```hcl
resource "vsphere_resource_pool" "resource_pool" {
  name                    = "SANDBOX"
  parent_resource_pool_id = data.vsphere_compute_cluster.compute_cluster.resource_pool_id}
}
```

Ryan

**Comment by tejavar** [comment]
Here is the vars.tf

```

data "vsphere_datacenter" "dc" {
  name = "${var.datacenter}"
}

data "vsphere_resource_pool" "pool" {
  name          = "${var.resource_pool}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_datastore" "ds" {
  name          = "${var.datastore}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}





data "vsphere_compute_cluster" "compute_cluster" {
  name          = "SANDBOX-FI"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

variable "datacenter" {
  default = "Dovetail-Core"
}

variable "datastore" {
  default = "x210c-esxi-shared"
}

variable "cluster" {
  default = "SANDBOX-FI"
}

variable "resource_pool" {
  description = "The resource pool to deploy the virtual machines to. If specifying a the root resource pool of a cluster, enter CLUSTER_NAME/Resources."
  default = "SANDBOX"
}


variable "dns_list" {
  default = "10.9.15.1"
}
```

**Comment by tenthirtyam** [comment]
The following full example takes the root resource pool path (`/<datacenter>/host/<clusterName>/Resources/`" and single plan dependencies into consideration.

`variables.tf`

```hcl
# Credentials

variable "vsphere_server" {
  type = string
}

variable "vsphere_username" {
  type = string
}

variable "vsphere_password" {
  type = string
}

variable "vsphere_insecure" {
  type    = bool
  default = false
}

# vSphere Settings

variable "vsphere_datacenter" {
  type = string
}

variable "vsphere_cluster" {
  type = string
}

variable "vsphere_datastore" {
  type = string
}

variable "vsphere_folder" {
  type = string
}

variable "vsphere_network" {
  type = string
}

variable "vsphere_template" {
  type = string
}

variable "vsphere_resource_pool" {
  type = string
}

# Virtual Machine Settings

variable "vm_name" {
  type = string
}

variable "vm_cpus" {
  type = number
}

variable "vm_memory" {
  type = number
}

variable "vm_disk_size" {
  type = number
}

variable "vm_firmware" {
  type = string
}

variable "vm_efi_secure_boot_enabled" {
  type = bool
}
```

`main.tf`
```
terraform {
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = ">= 2.0.2"
    }
  }
  required_version = ">= 1.1.5"
}

provider "vsphere" {
  vsphere_server       = var.vsphere_server
  user                 = var.vsphere_username
  password             = var.vsphere_password
  allow_unverified_ssl = var.vsphere_insecure
}

data "vsphere_datacenter" "datacenter" {
  name = var.vsphere_datacenter
}

data "vsphere_network" "network" {
  name          = var.vsphere_network
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_compute_cluster" "compute_cluster" {
  name          = var.vsphere_cluster
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_resource_pool" "root" {
  name          = format("%s%s", data.vsphere_compute_cluster.compute_cluster.name, "/Resources")
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_datastore" "datastore" {
  name          = var.vsphere_datastore
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_virtual_machine" "template" {
  name          = var.vsphere_template
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_resource_pool" "resource_pool" {
  depends_on = [
    vsphere_resource_pool.resource_pool,
  ]
  name          = var.vsphere_resource_pool
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_resource_pool" "resource_pool" {
  name                    = var.vsphere_resource_pool
  parent_resource_pool_id = data.vsphere_resource_pool.root.id
}

resource "vsphere_virtual_machine" "vm" {
  depends_on = [
    vsphere_resource_pool.resource_pool,
  ]
  name                    = var.vm_name
  num_cpus                = var.vm_cpus
  memory                  = var.vm_memory
  firmware                = var.vm_firmware
  efi_secure_boot_enabled = var.vm_efi_secure_boot_enabled
  folder                  = var.vsphere_folder
  guest_id                = data.vsphere_virtual_machine.template.guest_id
  datastore_id            = data.vsphere_datastore.datastore.id
  resource_pool_id        = data.vsphere_resource_pool.resource_pool.id
  network_interface {
    network_id = data.vsphere_network.network.id
  }
  cdrom {
    client_device = true
  }
  disk {
    label            = "disk0"
    size             = var.vm_disk_size
    eagerly_scrub    = false
    thin_provisioned = true
    datastore_id     = data.vsphere_datastore.datastore.id
  }
  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
  }
  lifecycle {
    ignore_changes = [
      clone[0].template_uuid
    ]
  }
  extra_config = {
    "guestinfo.metadata"          = base64encode(file("${path.module}/metadata.yml"))
    "guestinfo.metadata.encoding" = "base64"
    "guestinfo.userdata"          = base64encode(file("${path.module}/userdata.yml"))
    "guestinfo.userdata.encoding" = "base64"
  }
}
```

**Comment by tenthirtyam** [comment]
Marking this issue as closed. based on t[he previous example solution](https://github.com/hashicorp/terraform-provider-vsphere/issues/1582#issuecomment-1036623984).

If this issue is reproducible with the [latest](https://github.com/hashicorp/terraform-provider-vsphere/releases/latest) version of the provider, please comment. 

If you feel this issue should be reopened, we encourage creating a new issue linking back to this one for added context.

Thank you!

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
