### ISSUE TITLE
fatal error: runtime: out of memory - while uploading ISOs to vsphere_content_library_item

### ISSUE THREAD

**Issue by lapawa** [hashicorp/terraform-provider-vsphere#1638]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.1.7 on linux_amd64

### Terraform Provider

v2.1.1

### VMware vSphere

v7.0.3

### Description

Uploading multiple ISO images in parallel with size of e.g. 5.6G to a content library fails with an out of memory exception.

### Affected Resources

resource/vsphere_content_library_item

### Terraform Configuration

``

### Panic Output

❯ terraform apply
vsphere_content_library.iso_images_ffm01_published: Refreshing state... [id=5376cdc9-1045-4c76-9843-9e7118b721a6]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vsphere_content_library_item.content_library_item_iso_debian_10_netinst will be created
  + resource "vsphere_content_library_item" "content_library_item_iso_debian_10_netinst" {
      + description = "debian-10.3.0-amd64-netinst.iso"
      + file_url    = "http://images.ce.msys.net/debian/debian-10-netinst.iso"
      + id          = (known after apply)
      + library_id  = "5376cdc9-1045-4c76-9843-9e7118b721a6"
      + name        = "iso-images_debian-10-netinst"
      + type        = "iso"
    }

  # vsphere_content_library_item.content_library_item_iso_windows_server_2016 will be created
  + resource "vsphere_content_library_item" "content_library_item_iso_windows_server_2016" {
      + description = "SW_DVD9_Win_Server_STD_CORE_2016_64Bit_English_-4_DC_STD_MLF_X21-70526.ISO"
      + file_url    = "http://images.ce.msys.net/windows/windows-server-2016.iso"
      + id          = (known after apply)
      + library_id  = "5376cdc9-1045-4c76-9843-9e7118b721a6"
      + name        = "iso-images_windows-server-2016"
      + type        = "iso"
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes
vsphere_content_library_item.content_library_item_iso_windows_server_2016: Creating...                                                                                                                      [82/277]
vsphere_content_library_item.content_library_item_iso_debian_10_netinst: Creating...
vsphere_content_library_item.content_library_item_iso_windows_server_2016: Still creating... [10s elapsed]
vsphere_content_library_item.content_library_item_iso_debian_10_netinst: Still creating... [10s elapsed]
vsphere_content_library_item.content_library_item_iso_windows_server_2016: Still creating... [20s elapsed]
vsphere_content_library_item.content_library_item_iso_debian_10_netinst: Still creating... [20s elapsed]
vsphere_content_library_item.content_library_item_iso_debian_10_netinst: Still creating... [30s elapsed]
vsphere_content_library_item.content_library_item_iso_windows_server_2016: Still creating... [30s elapsed]
╷
│ Error: Request cancelled
│
│   with vsphere_content_library_item.content_library_item_iso_debian_10_netinst,
│   on contentlibraries-resource.tf line 25, in resource "vsphere_content_library_item" "content_library_item_iso_debian_10_netinst":
│   25: resource "vsphere_content_library_item" "content_library_item_iso_debian_10_netinst" {
│
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
╷
│ Error: Request cancelled
│
│   with vsphere_content_library_item.content_library_item_iso_windows_server_2016,
│   on contentlibraries-resource.tf line 33, in resource "vsphere_content_library_item" "content_library_item_iso_windows_server_2016":
│   33: resource "vsphere_content_library_item" "content_library_item_iso_windows_server_2016" {
│
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-vsphere plugin:

fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x176452c, 0x16)
        runtime/panic.go:1117 +0x72
runtime.sysMap(0xc2b4000000, 0x160000000, 0x23b1930)
        runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x2397cc0, 0x15ec00000, 0x42c017, 0x2397cc8)
        runtime/malloc.go:735 +0x1e5
runtime.(*mheap).grow(0x2397cc0, 0xaf598, 0x0)
        runtime/mheap.go:1346 +0x85
runtime.(*mheap).allocSpan(0x2397cc0, 0xaf598, 0x2370100, 0x1)
        runtime/mheap.go:1173 +0x609
runtime.(*mheap).alloc.func1()
        runtime/mheap.go:910 +0x59
runtime.systemstack(0x0)
        runtime/asm_amd64.s:379 +0x66
runtime.mstart()
        runtime/proc.go:1246
goroutine 44 [running]:                                                                                                                                                                                     [33/277]
runtime.systemstack_switch()
        runtime/asm_amd64.s:339 fp=0xc0009d2ff0 sp=0xc0009d2fe8 pc=0x46af20
runtime.(*mheap).alloc(0x2397cc0, 0xaf598, 0xc1f9b10001, 0x3a9d)
        runtime/mheap.go:904 +0x85 fp=0xc0009d3040 sp=0xc0009d2ff0 pc=0x427cc5
runtime.(*mcache).allocLarge(0x7fcfe7659a68, 0x15eb30000, 0xc000620100, 0xc1f9b16563)
        runtime/mcache.go:224 +0x97 fp=0xc0009d3098 sp=0xc0009d3040 pc=0x418337
runtime.mallocgc(0x15eb30000, 0x0, 0x3a00, 0x0)
        runtime/malloc.go:1084 +0x925 fp=0xc0009d3120 sp=0xc0009d3098 pc=0x40df65
runtime.growslice(0x1413300, 0xc0e1228000, 0x1188f2000, 0x1188f2000, 0x1188f2001, 0x0, 0x0, 0x1188f2000)
        runtime/slice.go:224 +0x154 fp=0xc0009d3188 sp=0xc0009d3120 pc=0x44e2b4
io.ReadAll(0x19f7aa0, 0xc00062c080, 0xc00062c080, 0x19f7aa0, 0xc00062c080, 0x0, 0x14ca240)
        io/io.go:631 +0x1d9 fp=0xc0009d3208 sp=0xc0009d3188 pc=0x49f579
io/ioutil.ReadAll(...)
        io/ioutil/ioutil.go:27
github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/ovfdeploy.GetOvfDescriptor(0xc0000451c0, 0x39, 0x10000, 0x0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/ovfdeploy/ovf_helper.go:284 +0x6c5 fp=0xc0009d3398 sp=0xc0009d3208 pc=0xed75a5
github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/contentlibrary.CreateLibraryItem(0xc00005aa80, 0xc0009fc750, 0xc0007f6920, 0x1e, 0xc000210dc0, 0x4a, 0xc0007baa80, 0x3, 0xc0000451c0, 0x39,
...)
        github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/contentlibrary/content_library_helper.go:202 +0x6ba fp=0xc0009d3668 sp=0xc0009d3398 pc=0xee5d9a
github.com/hashicorp/terraform-provider-vsphere/vsphere.resourceVSphereContentLibraryItemCreate(0xc000580f80, 0x14552e0, 0xc0005ae380, 0x0, 0xffffffffffffffff)
        github.com/hashicorp/terraform-provider-vsphere/vsphere/resource_vsphere_content_library_item.go:121 +0x41d fp=0xc0009d3750 sp=0xc0009d3668 pc=0x122097d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0002f8c40, 0x1a0fdc8, 0xc000962780, 0xc000580f80, 0x14552e0, 0xc0005ae380, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:318 +0x1ee fp=0xc0009d37c0 sp=0xc0009d3750 pc=0xae888e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002f8c40, 0x1a0fdc8, 0xc000962780, 0xc0002583f0, 0xc000636340, 0x14552e0, 0xc0005ae380, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:456 +0x67b fp=0xc0009d38a0 sp=0xc0009d37c0 pc=0xae989b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000c1c8, 0x1a0fdc8, 0xc000962780, 0xc000940cd0, 0xc000962780, 0x16de420, 0xc00096ed00)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:955 +0x8ef fp=0xc0009d3af0 sp=0xc0009d38a0 pc=0xae08af
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc0005af8e0, 0x1a0fe70, 0xc000962780, 0xc0002581c0, 0xc0005af8e0, 0xc00096ede0, 0xc00099dba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xb5 fp=0xc0009d3b40 sp=0xc0009d3af0 pc=0x99da75
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x16de420, 0xc0005af8e0, 0x1a0fe70, 0xc00096ede0, 0xc000565980, 0x0, 0x1a0fe70, 0xc00096ede0, 0xc000670$
00, 0x266)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214 fp=0xc0009d3bb0 sp=0xc0009d3b40 pc=0x994a94
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a9dc0, 0x1a19e18, 0xc000103680, 0xc00009a800, 0xc0005f8a20, 0x236f480, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b fp=0xc0009d3e50 sp=0xc0009d3bb0 pc=0x8d78eb
google.golang.org/grpc.(*Server).handleStream(0xc0002a9dc0, 0x1a19e18, 0xc000103680, 0xc00009a800, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c fp=0xc0009d3f68 sp=0xc0009d3e50 pc=0x8dbaac
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000483e0, 0xc0002a9dc0, 0x1a19e18, 0xc000103680, 0xc00009a800)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xab fp=0xc0009d3fb8 sp=0xc0009d3f68 pc=0x8e9a6b
runtime.goexit()
        runtime/asm_amd64.s:1371 +0x1 fp=0xc0009d3fc0 sp=0xc0009d3fb8 pc=0x46cc21
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

goroutine 1 [select]:
github.com/hashicorp/go-plugin.Serve(0xc000979e90)
        github.com/hashicorp/go-plugin@v1.4.1/server.go:469 +0x954
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve(0xc0002f7580)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/plugin/serve.go:122 +0xf4
main.main()
        github.com/hashicorp/terraform-provider-vsphere/main.go:9 +0x45

goroutine 8 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000214300)
        go.opencensus.io@v0.22.4/stats/view/worker.go:276 +0xcd
created by go.opencensus.io/stats/view.init.0
        go.opencensus.io@v0.22.4/stats/view/worker.go:34 +0x68
goroutine 9 [select]:
github.com/hashicorp/go-plugin.(*gRPCBrokerServer).Recv(0xc0005f8750, 0x0, 0x0, 0x0)
        github.com/hashicorp/go-plugin@v1.4.1/grpc_broker.go:121 +0x86
github.com/hashicorp/go-plugin.(*GRPCBroker).Run(0xc0001800f0)
        github.com/hashicorp/go-plugin@v1.4.1/grpc_broker.go:411 +0x7a
created by github.com/hashicorp/go-plugin.(*GRPCServer).Init
        github.com/hashicorp/go-plugin@v1.4.1/grpc_server.go:85 +0x39c

goroutine 10 [IO wait]:
internal/poll.runtime_pollWait(0x7fcfc098cdd0, 0x72, 0xffffffffffffffff)
        runtime/netpoll.go:227 +0x55
internal/poll.(*pollDesc).wait(0xc0001bc378, 0x72, 0x1001, 0x1000, 0xffffffffffffffff)
        internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0001bc360, 0xc0000cb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        internal/poll/fd_unix.go:166 +0x1d5
os.(*File).read(...)
        os/file_posix.go:31
os.(*File).Read(0xc00000e270, 0xc0000cb000, 0x1000, 0x1000, 0x400, 0x141cb40, 0x1)
        os/file.go:117 +0x77
bufio.(*Reader).Read(0xc000067f50, 0xc0001e7400, 0x400, 0x400, 0x0, 0x0, 0x0)
        bufio/bufio.go:227 +0x222
github.com/hashicorp/go-plugin.copyChan(0x1a1eb88, 0xc000532070, 0xc00018f320, 0x19f7cc0, 0xc00000e270)
        github.com/hashicorp/go-plugin@v1.4.1/grpc_stdio.go:181 +0xc5

Error: The terraform-provider-vsphere plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

Completing apply with successful uploaded items into the vSphere Content Library.

### Actual Behavior

Content library and items were created but content has 0 bytes and terraform itself paniced.

### Steps to Reproduce

Create a vsphere_content_library and vsphere_content_library_item  resource with an ISO image and a http url as content source.

**Comment by tenthirtyam** [comment]
Hi @lapawa, 👋 

Please update the **Terraform Configuration** in the issue with the redacted configuration(s) for reproduction.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by lapawa** [comment]
I've uploaded the configuration and added the gist link to the issues description.

**Comment by tenthirtyam** [comment]
Hi @lapawa - does the issue also present itself if you modify the API timeout in the provider block to increase the default? Is the issue consistent and repeatable?

Ryan

**Comment by lapawa** [comment]
It's the same with a api_timeout on the provider of 60.
It still crashes with: 
fatal error: runtime: out of memory 
and 
Error: The terraform-provider-vsphere plugin crashed!

And yes it is repeatable. I's only working when I upload a tiny ISO image like Debian netinstall.

**Comment by tenthirtyam** [comment]
Thanks, @lapawa. I'll take a look and see if I can reproduce the error when time and prioritization permits.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
I've taken quite some time to look at this issue, but have not been able to reproduce the exact same issue.

Rather, in my testing, I'm seeing that large or multiple remote (`HTTP` / `HTTPS`) .iso files are failing with a **500 Internal Server Error** HTTP status code.

I've even modified the provider's `CreateLibraryItem` function  (based on GH-1665) with the following snippets to call the desired function for remote .iso files:

```go
func CreateLibraryItem(c *rest.Client, l *library.Library, name string, desc string, t string, file string, moid string) (*string, error) {
   #...
	switch {
	case isLocal && isOva:
		return &id, uploadSession.deployLocalOva(file, ovfDescriptor)
	case isLocal && !isOva && !isIso:
		return &id, uploadSession.deployLocalOvf(file, ovfDescriptor)
	case isLocal && isIso:
		return &id, uploadSession.deployLocalIso(file)
	case !isLocal && isOva:
		return &id, uploadSession.deployRemoteOva(file, ovfDescriptor)
	case !isLocal && !isOva && !isIso:                           # <----- Updated
		return &id, uploadSession.deployRemoteOvf(file)
	case !isLocal && isIso:                                      # <----- Added
		return &id, uploadSession.deployRemoteIso(file)      # <----- Added
	}
   #...
}
```

and 

```go
func (uploadSession *libraryUploadSession) deployRemoteIso(file string) error {
	ctx := context.TODO()
	_, err := uploadSession.ContentLibraryManager.AddLibraryItemFileFromURI(ctx, uploadSession.UploadSession, filepath.Base(file), file)
	if err != nil {
		return err
	}
	return uploadSession.ContentLibraryManager.WaitOnLibraryItemUpdateSession(ctx, uploadSession.UploadSession, time.Second*10, func() { log.Printf("Waiting...") })
}
```

This would be similar to: 

```console
govc library.import iso-test https://releases.ubuntu.com/jammy/ubuntu-22.04-live-server-amd64.iso
```

However, even though the `AddLibraryItemFileFromURI` from `vmware/govmomi` is being used the .iso files seem to fail with the following in the vSphere client:

```console
Reason: Unable to update files in the library item. The source or destination may be slow or not responding.
```

It seems to be related to either/both the size of the .iso file and the number of files being uploaded to the content library. It does not seem to be related to HTTPS and SSL acceptance.

Labeling this issue with the `community/contribution` label in the event anyone has additional thoughts on how to enhance `vsphere/internal/helper/contentlibrary/content_library_helper.go` to help resolve this issue.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
Hi @juanvalino,

Based on your work in GH-1664, I was curious if you'd like to research this issue alongside [my prior comments](https://github.com/hashicorp/terraform-provider-vsphere/issues/1638#issuecomment-1148014568) and propose a contribution.

My review of the issue started to build off your contributions in PR GH-1665.

Let us know what you think.

Thanks!
Ryan

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by juanvalino** [comment]
@tenthirtyam I´m going to try to reproduce this in our plataform. As far as I known when you use remote files, vsphere is the responsible of the remote file download into the content library. Perhaps, there is some connectivity issue on the vshpere side that makes the download fails.

I'll keep you informed of my local testings.

**Comment by tenthirtyam** [comment]
Much appreciated, @juanvalino!

I'm leaning in the same line of reasoning since the download is not proxied.

Ryan

**Comment by juanvalino** [comment]
@tenthirtyam in my tests, a single remote ISO of 10GB (https://download.rockylinux.org/pub/rocky/8/isos/x86_64/Rocky-8.6-x86_64-dvd1.iso) ends with the same error: `500 Internal Server Error`

Uploading the same iso remote url using vcenter web user interface works perfectly.

Uploading the same iso from local file (not remote url) works perfectly.

Could be some timeout during vcenter API calls?

This problem is beyond my capabilities with terraform/vcenter 🙁

**Comment by tenthirtyam** [comment]
No worries @juanvalino - many thanks for your testing efforts. This confirms my suspicions as well and will review it more with I'm back from vacation.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by sneal** [comment]
I'll give this a try, but I'm guessing the TF provider is attempting to read the entire OVF/OVA into memory:

```
...
io/ioutil.ReadAll(...)
io/ioutil/ioutil.go:27
github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/ovfdeploy.GetOvfDescriptor(0xc0000451c0, 0x39, 0x10000, 0x0, 0x0, 0x0, 0x0)
...
```

**Comment by tenthirtyam** [comment]
Tracked it down about a week ago. 

It's doing a push to the target from the host Terraform is running over versus a pull from the vCenter Server instance itself.

The root cause appears to be that the call to the `AddLibraryItemFileFromURI` function is not resulting in the desired pull.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
Picking this one up to look at for v2.8.2 milestone. 

**Research Note**: Changes in PR #2219 may assist with this.

**Comment by tenthirtyam** [comment]
Possible that this might be resolved with the pending changes in #2427. Stay tuned.

**Comment by tenthirtyam** [comment]
The root cause is that the implementation is using the location where the plan is run as an intermediary and runs out of memory. The implementation should instruct remote items to be pulled.
